import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>KikiriCoin</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={`${styles.blockOuterWrapper} ${styles.coverBlock}`}>
          <div className={styles.blockContent}>
            <div className={styles.coverBlockInfo}>
              <h1 className={styles.title}>KikiriCoin</h1>
              <p>
                Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero
                la salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón.
                Pero calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi
                musculitos aquí no hay tomate.
              </p>
            </div>

            <div className={styles.coverBlockLogoContainer}>
              <Image src="/1f413.png" alt="Logo" width="250" height="250" />
            </div>
          </div>
        </div>

        <div className={styles.blockOuterWrapper}>
          <div className={styles.blockContent}>
            <h1 className={styles.title}>KikiriCoin</h1>

            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
          </div>
        </div>

        <div className={styles.blockOuterWrapper}>
          <div className={styles.blockContent}>
            <h1 className={styles.title}>KikiriCoin</h1>

            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
            <p>
              Jamón ipsum pinchito horchata atún orujo ligar borrachos como cubas. Un como motos turrón Quijote pero la
              salir de descafeinado cogió prestado una resacón, tiburón de la noche ronda hecho polvo botellón. Pero
              calimocho ancha es Castilla. Las abanica maruja caradura, los tomatito sangre fría quillo mi musculitos
              aquí no hay tomate.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
